# Install golang
---
- name: Download .tar
  ansible.builtin.get_url:
    url: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ go_dl_tar }}"
    mode: '0755'

- name: "Copy pasta from official golang website"
  become: true
  changed_when: false
  ansible.builtin.shell: |
    rm -rf /usr/local/go && tar -C /usr/local -xzf "{{ go_dl_tar }}"
