# Install nivm
---
- name: "Download appimage"
  become: true
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
    dest: /usr/local/bin/nvim
    force: true
    mode: "0755"

- name: "Remove packages"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim"
    state: absent
